# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gareth Hunt
email: ghunt03@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ghunt03.github.io" # the base hostname & protocol for your site
twitter_username: ghunt03
github_username:  ghunt03
linked_in: https://au.linkedin.com/in/ghunt03
# Build settings
markdown: kramdown

sass:
    sass_dir: _sass
